AND-3578: allow to select any available curve in DemoApp
tangem/tangem-sdk-android-old pull request #278
Opened 2023-05-17 07:02 UTC by roman-pv

2023-05-17 07:50 UTC, Mama1emon requested changes

2023-05-17 07:50 UTC, Mama1emon commented on tangem-sdk-android-demo/src/main/java/com/tangem/demo/ui/separtedCommands/CommandListFragment.kt
> +                spinnerCurves.selectedItem as EllipticCurve,
Предлагаю использовать безопасный каст, так как есть шанс, что если кто-то изменит тип данных, то есть шанс нарваться на рантайм ошибку

2023-05-17 08:14 UTC, roman-pv commented on tangem-sdk-android-demo/src/main/java/com/tangem/demo/ui/separtedCommands/CommandListFragment.kt
> +                spinnerCurves.selectedItem as EllipticCurve,
это демо приложение для внутреннего пользования, зачем тут осторожничать? ну нарвемся, поправим

2023-05-17 08:47 UTC, kozarezvlad approved these changes

2023-05-18 06:38 UTC, roman-pv commented on tangem-sdk-android-demo/src/main/java/com/tangem/demo/ui/separtedCommands/CommandListFragment.kt
> +                spinnerCurves.selectedItem as EllipticCurve,
@Mama1emon

2023-05-18 06:57 UTC, Mama1emon commented on tangem-sdk-android-demo/src/main/java/com/tangem/demo/ui/separtedCommands/CommandListFragment.kt
> +                spinnerCurves.selectedItem as EllipticCurve,
Не совсем понимаю идею "писать небезопасный код, чтобы потом, если вдруг что-то случится, то исправить". Как мне кажется, это чревато тратой дополнительного времени и ресурсов команды, чего можно легко избежать

2023-05-18 07:05 UTC, roman-pv commented on tangem-sdk-android-demo/src/main/java/com/tangem/demo/ui/separtedCommands/CommandListFragment.kt
> +                spinnerCurves.selectedItem as EllipticCurve,
Так тут вопрос не в этом. "Безопасный каст" - это значит, что когда ты изменил тип данных и сломал спиннер, то ты не узнаешь сразу об этом, а будешь получать дефолтную кривую. Это вообще не нужно в этом приложении, нам наоборот надо сразу знать, если мы сломали это. Есть же два подхода к обработке ошибок - break fast или наоборот прячь поломку. Когда речь идет о релизном приложении, чаще нужен второй подход. Во внутреннем - первый часто полезнее.

2023-05-18 07:06 UTC, roman-pv commented on tangem-sdk-android-demo/src/main/java/com/tangem/demo/ui/separtedCommands/CommandListFragment.kt
> +                spinnerCurves.selectedItem as EllipticCurve,
То есть нам и так, и так исправлять надо будет. Но в текущем виде мы сразу это узнаем. В "безопасном" не сразу

2023-05-18 07:14 UTC, Mama1emon commented on tangem-sdk-android-demo/src/main/java/com/tangem/demo/ui/separtedCommands/CommandListFragment.kt
> +                spinnerCurves.selectedItem as EllipticCurve,
Безопасный каст требует специальной обработки ошибок, например, использование `requireNotNull()`, с помощью чего и будет соблюден тот подход, о котором ты говоришь

2023-05-18 07:18 UTC, Mama1emon commented on tangem-sdk-android-demo/src/main/java/com/tangem/demo/ui/separtedCommands/CommandListFragment.kt
> +                spinnerCurves.selectedItem as EllipticCurve,
Пусть остается на твое усмотрение. Если остальных такой подход устраивает, я не буду блочить

2023-05-18 07:32 UTC, roman-pv commented on tangem-sdk-android-demo/src/main/java/com/tangem/demo/ui/separtedCommands/CommandListFragment.kt
> +                spinnerCurves.selectedItem as EllipticCurve,
Если команда считает, что безопасный каст и requireNotNull() { } будет понятнее, чем так, то ок. В данном контексте не вижу преимущества.

2023-05-18 07:38 UTC, gbixahue approved these changes

2023-05-18 07:48 UTC, iiiburnyiii approved these changes

2023-05-18 07:49 UTC, Mama1emon approved these changes

2023-05-18 07:54 UTC, merged