AND-3607: return cardID in BackupFailedNotEmptyWallets error
tangem/tangem-sdk-android-old pull request #285
Opened 2023-05-23 07:43 UTC by roman-pv

2023-05-24 12:14 UTC, Yoggam1 approved these changes

2023-05-24 13:17 UTC, Sateetas approved these changes

2023-05-25 06:10 UTC, Mama1emon requested changes

2023-05-25 06:10 UTC, Mama1emon commented on tangem-sdk-core/src/main/java/com/tangem/common/core/TangemError.kt
> +    class BackupFailedNotEmptyWallets(val cardId: String) : TangemSdkError(code = 41210)
А где используется данный параметр? В изменениях только то, что он сеттится

2023-05-25 13:52 UTC, roman-pv commented on tangem-sdk-core/src/main/java/com/tangem/common/core/TangemError.kt
> +    class BackupFailedNotEmptyWallets(val cardId: String) : TangemSdkError(code = 41210)
в приложении

2023-05-25 13:53 UTC, roman-pv commented on tangem-sdk-core/src/main/java/com/tangem/common/core/TangemError.kt
> +    class BackupFailedNotEmptyWallets(val cardId: String) : TangemSdkError(code = 41210)
ошибки же наружу идут, в рамках сдк везде и так известен номер карты

2023-05-25 13:57 UTC, roman-pv commented on tangem-sdk-core/src/main/java/com/tangem/common/core/TangemError.kt
> +    class BackupFailedNotEmptyWallets(val cardId: String) : TangemSdkError(code = 41210)
а почему ты выбираешь reqest changes, когда ты задаешь вопросы?)

2023-05-26 07:42 UTC, kozarezvlad approved these changes

2023-05-26 09:59 UTC, Mama1emon commented on tangem-sdk-core/src/main/java/com/tangem/common/core/TangemError.kt
> +    class BackupFailedNotEmptyWallets(val cardId: String) : TangemSdkError(code = 41210)
Потому что хочу получить ответ на вопрос)

2023-05-26 10:00 UTC, Mama1emon approved these changes

2023-05-26 10:35 UTC, merged