AND-3561: add master key creation for BLS
tangem/tangem-sdk-android-old pull request #292
Opened 2023-05-31 11:31 UTC by roman-pv

2023-05-31 13:39 UTC, iiiburnyiii requested changes

2023-05-31 13:39 UTC, iiiburnyiii commented on tangem-sdk-core/src/main/java/com/tangem/common/MasterKeyFactory.kt
> +    @Throws
Надо бы указать, что отсюда может вылететь

2023-05-31 13:39 UTC, iiiburnyiii commented on tangem-sdk-core/src/main/java/com/tangem/common/MasterKeyFactory.kt
> +    @Throws
Либо просто убрать)

2023-05-31 13:39 UTC, iiiburnyiii commented on tangem-sdk-core/src/main/java/com/tangem/crypto/Bls.kt
> +    // / Version of keygen algorithm prior to number 4 (used in
Этот коммент не дописан?

2023-05-31 13:39 UTC, iiiburnyiii commented on tangem-sdk-core/src/main/java/com/tangem/crypto/Bls.kt
> +    @Throws
Тут тож можно выпилить или дополнить

2023-05-31 13:39 UTC, iiiburnyiii commented on tangem-sdk-core/src/main/java/com/tangem/crypto/CryptoUtils.kt
> +                throw UnsupportedOperationException()
Может ту же ошибку оставить? Она выглядит как более подходящая

2023-05-31 13:39 UTC, iiiburnyiii commented on build.gradle
> +        versions.kotlin = '1.7.21'
А есть возможность поднять до 1.8.21, что-бы версия такая же как и в app была

2023-05-31 13:39 UTC, iiiburnyiii commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-bin.zip
Может можно до 8.0.2 поднять?

2023-05-31 16:35 UTC, roman-pv commented on tangem-sdk-core/src/main/java/com/tangem/crypto/Bls.kt
> +    // / Version of keygen algorithm prior to number 4 (used in
да, слово не описал случайно

2023-05-31 16:37 UTC, roman-pv commented on build.gradle
> +        versions.kotlin = '1.7.21'
Попробовал, нам надо тогда переписать в demo app с ktx на viewbinding или компоуз. 
Наверное лучше отдельной задачей )

2023-06-05 06:16 UTC, roman-pv commented on tangem-sdk-core/src/main/java/com/tangem/crypto/CryptoUtils.kt
> +                throw UnsupportedOperationException()
Все-таки здесь думаю лучше оставить UnsupportedOperationException, как и в других соседних функциях, потому что смысл не в том, что мы здесь эту кривую не поддерживаем, в том, что с этой кривой это именно что UnsupportedOperation

2023-06-07 08:49 UTC, Mama1emon approved these changes

2023-06-07 09:07 UTC, Sateetas commented on tangem-sdk-core/src/main/java/com/tangem/common/MasterKeyFactory.kt
> +    @Throws
да, я бы убрал
или прям нужен checked exception?

2023-06-07 09:46 UTC, Sateetas requested changes

2023-06-07 09:46 UTC, Sateetas commented on tangem-sdk-android/src/main/java/com/tangem/sdk/ui/widget/PinCodeRequestWidget.kt
> +            else -> Unit
Я стараюсь избегать else-бренчей, когда делаем when по sealed-классу

Предлагаю добавить перечисление всех остальных подклассов, хотя это будет занимать несколько строк

Тогда в случае, если появился еще один наследник, то мы на этапе компиляции получим ошибку о том, что реализации его обработки нет

При текущей реализации возможная ошибка будет скрыта
Таким образом мы задаем более строгий контракт, пусть и путем увеличения количества кода

2023-06-07 09:46 UTC, Sateetas commented on tangem-sdk-core/src/main/java/com/tangem/crypto/Bls.kt
> +            else -> throw TangemSdkError.UnsupportedCurve()
здесь аналогично предыдущему комментарию с точностью до sealed class/enum

2023-06-07 09:46 UTC, Sateetas commented on tangem-sdk-core/src/main/java/com/tangem/crypto/CryptoUtils.kt
> +                throw UnsupportedOperationException()
тогда лучше с описанием ошибки в конструкторе эксепшна

2023-06-08 06:00 UTC, roman-pv commented on tangem-sdk-core/src/main/java/com/tangem/crypto/Bls.kt
> +            else -> throw TangemSdkError.UnsupportedCurve()
здесь так не нужно, проход только по Bls12381G2 кривым, остальные игнорируются. Else здесь правильнее и нагляднее

2023-06-08 06:06 UTC, roman-pv commented on tangem-sdk-core/src/main/java/com/tangem/crypto/CryptoUtils.kt
> +                throw UnsupportedOperationException()
А тут ничего особенного не опишешь, это и есть UnsupportedOperation для этих кривых

2023-06-08 06:11 UTC, roman-pv commented on tangem-sdk-android/src/main/java/com/tangem/sdk/ui/widget/PinCodeRequestWidget.kt
> +            else -> Unit
здесь ситуация примерно как в другом месте, где ты это описал. У нас здесь нужна обработка стейтов, только связанных с пин кодами. Все остальные стейты здесь не обрабатываются. В таком случае на мой взгляд понятнее, когда используется else. Если мы будем добавлять новый стейт, скорее всего он не будет здесь обрабатываться так же, и нам не нужно будет править этот файл, чтобы еще один when добавить. А если какой-то новый стейт будет здесь обрабатываться, то мы точно не забудем его здесь упомянуть

2023-06-08 06:12 UTC, roman-pv commented on tangem-sdk-core/src/main/java/com/tangem/crypto/CryptoUtils.kt
> +                throw UnsupportedOperationException()
Если я добавлю описание в ошибку "This operation is not supported for this curve", я не скажу ничего того, что уже не задано названием ошибки )

2023-06-08 07:51 UTC, iiiburnyiii approved these changes

2023-06-08 07:59 UTC, Sateetas commented on tangem-sdk-core/src/main/java/com/tangem/crypto/Bls.kt
> +            else -> throw TangemSdkError.UnsupportedCurve()
а если еще одна Bls12381G2 появится?

2023-06-08 08:29 UTC, roman-pv commented on tangem-sdk-core/src/main/java/com/tangem/crypto/Bls.kt
> +            else -> throw TangemSdkError.UnsupportedCurve()
Это маловероятно, и в таком случае поправить файл при необходимости будет проще, чем править его каждый при появлении других кривых, что намного более вероятно.
На мой взгляд потенциальное преимущество в подобном кейсе меньше более регулярного неудобства. И в плане содержания так понятнее, что здесь перебор только по схемам для bls кривых

2023-06-08 09:56 UTC, Sateetas approved these changes

2023-06-08 10:45 UTC, merged