AND-4145: add support for new Ed25519Slip0010
tangem/tangem-sdk-android-old pull request #310
Opened 2023-08-09 11:30 UTC by roman-pv

2023-08-09 13:30 UTC, kozarezvlad requested changes

2023-08-09 13:30 UTC, kozarezvlad commented on tangem-sdk-core/src/main/java/com/tangem/common/card/FirmwareVersion.kt
> +        val KeysImportAvailable = FirmwareVersion(6, 33)
Надо похоже откатить, в ios зашились на Ed25519Slip0010Available

2023-08-09 15:06 UTC, Mama1emon approved these changes, later dismissed

2023-08-09 15:15 UTC, kozarezvlad commented on tangem-sdk-core/src/main/java/com/tangem/common/card/EllipticCurve.kt
> +    fun supportsDerivation(): Boolean {
а bls сюда не надо?

2023-08-09 15:15 UTC, kozarezvlad commented on tangem-sdk-core/src/main/java/com/tangem/crypto/hdWallet/bip32/BIP32.kt
> +            // we use Ikarus master key generation scheme for this curve
Мб в лог что то писать еще?

2023-08-09 16:45 UTC, roman-pv commented on tangem-sdk-core/src/main/java/com/tangem/crypto/hdWallet/bip32/BIP32.kt
> +            // we use Ikarus master key generation scheme for this curve
Мы выше в месте вызова кинем ошибку, что UnsupportedCurve, думаю этого достаточно

2023-08-09 16:50 UTC, roman-pv commented on tangem-sdk-core/src/main/java/com/tangem/common/card/EllipticCurve.kt
> +    fun supportsDerivation(): Boolean {
нет, он в false

2023-08-10 07:13 UTC, kozarezvlad approved these changes

2023-08-10 07:55 UTC, gbixahue approved these changes

2023-08-10 07:55 UTC, gbixahue commented on tangem-sdk-android-demo/src/main/java/com/tangem/demo/ui/BaseFragment.kt
> +
А для чего в when начали добавлять эти лишние пустые строки?

2023-08-10 08:48 UTC, merged